dist: xenial
language: cpp
compiler: clang
addons:
  apt:
    sources:
      - llvm-toolchain-xenial-8
    packages:
      - clang-8
before_install:
- export CC=clang-8
- export CXX=clang++-8
install:
- pip install --user conan
- conan user
script:
- conan install .
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T ip_filter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ugpgolikov:$BINTRAY_API_KEY "https://api.bintray.com/content/gpgolikov/otus-cpp/homework/$TRAVIS_BUILD_NUMBER/ip_filter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"

